# Generated by Django 4.2.4 on 2023-11-24 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.IntegerField(blank=True, null=True)),
                ('fin_prdt_cd', models.TextField(blank=True, null=True)),
                ('fin_prdt_nm', models.TextField(blank=True, null=True)),
                ('kor_co_nm', models.TextField(blank=True, null=True)),
                ('dcls_strt_day', models.IntegerField(blank=True, null=True)),
                ('dcls_end_day', models.IntegerField(blank=True, null=True)),
                ('join_deny', models.IntegerField(blank=True, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('save_trm', models.IntegerField(blank=True, null=True)),
                ('intr_rate_type', models.TextField(blank=True, null=True)),
                ('intr_rate_type_nm', models.TextField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('rsrv_type', models.TextField(blank=True, null=True)),
                ('rsrv_type_nm', models.TextField(blank=True, null=True)),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.savingproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.IntegerField(blank=True, null=True)),
                ('fin_prdt_cd', models.TextField(blank=True, null=True)),
                ('fin_prdt_nm', models.TextField(blank=True, null=True)),
                ('kor_co_nm', models.TextField(blank=True, null=True)),
                ('dcls_strt_day', models.IntegerField(blank=True, null=True)),
                ('dcls_end_day', models.IntegerField(blank=True, null=True)),
                ('join_deny', models.IntegerField(blank=True, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('save_trm', models.IntegerField(blank=True, null=True)),
                ('intr_rate_type', models.TextField(blank=True, null=True)),
                ('intr_rate_type_nm', models.TextField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('deposit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.depositproduct')),
            ],
        ),
    ]
